export const GET_MEDIA_DATA = "GET_MEDIA_DATA";
export const FILTER_MEDIA_DATA = "FILTER_MEDIA_DATA";
export const ACTIVATE_SEARCH = "ACTIVATE_SEARCH";
export const CHANGE_CARD_STATUS = "CHANGE_CARD_STATUS";